ALTER USER 'root'@'localhost' IDENTIFIED BY '1234';
SET PASSWORD = PASSWORD('1234');
CREATE USER 'simpla'@'192.168.1.%' IDENTIFIED BY '1234';
CREATE USER 'simpla'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES on *.* TO 'simpla'@'192.168.1.%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES on *.* TO 'simpla'@'localhost' WITH GRANT OPTION;
CREATE DATABASE simpla;
FLUSH PRIVILEGES;
